### ISSUE TITLE
移动端 vw 布局实现 1px 边框线的 scss mixin

### ISSUE THREAD

**Issue by yinxin630** [yinxin630/blog#28]
```scss
$border-poses: top, right, bottom, left;
$border-color: #eee;
@mixin border-1px($color: $border-color, $poses: $border-poses) {
    position: relative;
    &::after {
        content: '';
        display: block;
        position: absolute;
        width: 100%;
        @each $pos in $poses {
            border-#{$pos}: 1px solid $color;
            #{$pos}: 0;
        }
        @if $poses == 'top' or $poses == 'bottom' {
            left: 0;
            right: 0;
        }
        @if $poses == 'left' or $poses == 'right' {
            top: 0;
            bottom: 0;
        }
    }
}
```
